server:
  port: 9527

spring:
  application:
    name: gateway-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true

        service-name: ${spring.application.name}

    gateway:
      routes:
        - id: businessService
          uri: lb://service-provider
          predicates:
            - Path=/business/**

